import { CareerMapType } from './careerType';

export const writing: CareerMapType[] = [
  {
    seo: {
      title: 'copywriting Tread: Learn to become a modern copywriting expert',
      description:
        'Learn to become a modern copy writer using this roadmap. Community driven, articles, resources, guides, interview questions, quizzes for modern copywriting.',
      keywords: [
        'copy writer roadmap 2022',
        'copywriting roadmap 2022',
        'copywriting path 2022',
        'copywriting tread 2022',
        'guide to becoming a writer',
        'guide to becoming a copywriting',
        'copywriting',
        'copy writer',
        'copywriting',
        'copywriting skills',
        'copywriting skills test',
        'copy writer roadmap',
        'copywriting roadmap',
        'become a copywriter',
        'copywriting career path',
        'copy writer expert',
        'modern copy writer expert',
        'node developer',
        'skills for copywriting',
        'learn copywriting',
        'what is copywriting',
        'copywriting quiz',
        'copywriting interview questions',
      ],
    },
    title: 'copywriting',
    description: 'Step by step guide to becoming a modern copywriter in 2022',
    featuredTitle: 'copywriting',
    featuredDescription: 'Step by step guide to becoming a copywriting in 2022',
    featured: true,
    pdfUrl: '',
    contentPathsFilePath: '/careers/writing/copywriting/content-paths.json',
    id: 'copywriting',
    parentId: 'writing',
    isUpcoming: false,
  },
];
